services:
  db:
    image: postgres:16-alpine
    container_name: time_manage_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: time_manage_db
      POSTGRES_USER: pupuser
      POSTGRES_PASSWORD: botinki
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  time-manage-max-bot:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: time-manage-max-bot
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/time_manage_db"
      SPRING_DATASOURCE_USERNAME: "pupuser"
      SPRING_DATASOURCE_PASSWORD: "botinki"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"


volumes:
  db_data:
