spring:
  datasource:
    url: jdbc:postgresql://db:5432/time_manage_db
    username: pupuser
    password: botinki
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # ← ЭТИ ДВЕ СТРОЧКИ — КРИТИЧНО! camelCase без подчёркиваний
        entityManagerFactoryInterface: jakarta.persistence.EntityManagerFactory
        sessionFactoryInterface: org.hibernate.SessionFactory

server:
  address: 0.0.0.0
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.hack.botinki: DEBUG

max:
  bot: 
    token: f9LHodD0cOJ6Jy-WoRkcldBDgZ2cvifn3rvYs-UMKLvYF7v231WVWgyyUDcX3VIk99XqZKfTmw_1GyEtTpe3
    verify-token: capi-capi-token-00
  api:
    url: https://platform-api.max.ru
  app:
    url: https://hack-front-v1.vercel.app/?user_id=


